### ISSUE TITLE
Include the data sets

### ISSUE THREAD

**Issue by steven-joruk** [ryanberckmans/eqoptimizer#3]
This is very specific to Medievia, so including the data sets would be great. It's hard to create good item databases as so few people play, there's not much to scrape from auctions and the catalog. Even a minimal example data set would be good. Cheers.

**Comment by ryanberckmans** [comment]
@steven-joruk a link to my data files for EqOptimizer has been added to the README. It includes comprehensive max eq for most class/align spanning many years. There's even a few famous sets in the files, such as Mitrimy's nmage set and Daedalus' ethief from 2004. Sorry it took so long. Happy holidays.
